# Generated by Django 3.0.6 on 2020-10-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('purchased', models.BooleanField(default=False)),
            ],
        ),
    ]
