# Generated by Django 3.0.6 on 2020-10-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
