# Generated by Django 3.0.6 on 2020-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
