# Generated by Django 3.0.6 on 2020-10-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('painted', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=50)),
                ('lid', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Lprice', models.IntegerField(default=None)),
                ('Mprice', models.IntegerField(default=None)),
                ('Sprice', models.IntegerField(default=None)),
                ('Large', models.BooleanField(default=False)),
                ('Medium', models.BooleanField(default=False)),
                ('Small', models.BooleanField(default=False)),
                ('Ldimension', models.CharField(max_length=50)),
                ('Mdimension', models.CharField(max_length=50)),
                ('Sdimension', models.CharField(max_length=50)),
                ('Lstock', models.IntegerField(default=10)),
                ('Mstock', models.IntegerField(default=10)),
                ('Sstock', models.IntegerField(default=10)),
            ],
        ),
    ]
