# Generated by Django 3.0.6 on 2020-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('sizes', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('colours', models.CharField(max_length=50)),
            ],
        ),
    ]
